# This is a basic workflow to help you get started with Actions

name: Server

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Public IP
        run: curl ifconfig.me
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
              # git clone https://github.com/vancelmusic/minecraft-server.git /mc-server
              # cd mc-server
              java -Xmx1G -jar server.jar nogui
              
