# This is a basic workflow to help you get started with Actions

name: Server

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:

    runs-on: ubuntu-18.04
    defaults:
        run:
            working-directory: ./
    
    steps:
      - name: Public IP
        run: curl ifconfig.me
      
      # Runs a set of commands using the runners shell
      - name: Server Start
        run: |
             # git clone https://github.com/vancelmusic/minecraft-server.git $HOME/MC
            java -Xmx1G -jar $HOME/server.jar nogui
